/*
 * DIO_cfg.h
 *
 *  Created on: 10 Dec 2023
 *      Author: user
 */

#ifndef DIO_CFG_H_
#define DIO_CFG_H_

#define PIN_DIRECTION_OUT	1
#define PIN_DIRECTION_IN	0

#define PIN_VALUE_HIGH	1
#define PIN_VALUE_LOW	0

/*		PORTA CONFIGURATION		*/

#define PORTA_PIN0_DIRECTION	PIN_DIRECTION_IN
#define PORTA_PIN1_DIRECTION	PIN_DIRECTION_OUT
#define PORTA_PIN2_DIRECTION	PIN_DIRECTION_IN
#define PORTA_PIN3_DIRECTION	PIN_DIRECTION_IN
#define PORTA_PIN4_DIRECTION	PIN_DIRECTION_IN
#define PORTA_PIN5_DIRECTION	PIN_DIRECTION_IN
#define PORTA_PIN6_DIRECTION	PIN_DIRECTION_IN
#define PORTA_PIN7_DIRECTION	PIN_DIRECTION_IN


/*		PORTB CONFIGURATION		*/

#define PORTB_PIN0_DIRECTION	PIN_DIRECTION_IN
#define PORTB_PIN1_DIRECTION	PIN_DIRECTION_IN
#define PORTB_PIN2_DIRECTION	PIN_DIRECTION_IN
#define PORTB_PIN3_DIRECTION	PIN_DIRECTION_IN
#define PORTB_PIN4_DIRECTION	PIN_DIRECTION_IN
#define PORTB_PIN5_DIRECTION	PIN_DIRECTION_IN
#define PORTB_PIN6_DIRECTION	PIN_DIRECTION_IN
#define PORTB_PIN7_DIRECTION	PIN_DIRECTION_IN


/*		PORTC CONFIGURATION		*/

#define PORTC_PIN0_DIRECTION	PIN_DIRECTION_IN
#define PORTC_PIN1_DIRECTION	PIN_DIRECTION_IN
#define PORTC_PIN2_DIRECTION	PIN_DIRECTION_IN
#define PORTC_PIN3_DIRECTION	PIN_DIRECTION_IN
#define PORTC_PIN4_DIRECTION	PIN_DIRECTION_IN
#define PORTC_PIN5_DIRECTION	PIN_DIRECTION_IN
#define PORTC_PIN6_DIRECTION	PIN_DIRECTION_IN
#define PORTC_PIN7_DIRECTION	PIN_DIRECTION_IN


/*		PORTD CONFIGURATION		*/

#define PORTD_PIN0_DIRECTION	PIN_DIRECTION_IN
#define PORTD_PIN1_DIRECTION	PIN_DIRECTION_IN
#define PORTD_PIN2_DIRECTION	PIN_DIRECTION_IN
#define PORTD_PIN3_DIRECTION	PIN_DIRECTION_IN
#define PORTD_PIN4_DIRECTION	PIN_DIRECTION_IN
#define PORTD_PIN5_DIRECTION	PIN_DIRECTION_IN
#define PORTD_PIN6_DIRECTION	PIN_DIRECTION_IN
#define PORTD_PIN7_DIRECTION	PIN_DIRECTION_IN



#define PORTA_DIRECTION_CONFIG(PORTA_PIN0_DIRECTION,PORTA_PIN1_DIRECTION,PORTA_PIN2_DIRECTION,PORTA_PIN3_DIRECTION,PORTA_PIN4_DIRECTION,PORTA_PIN5_DIRECTION,PORTA_PIN6_DIRECTION,PORTA_PIN7_DIRECTION) (PORTA_PIN0_DIRECTION + (PORTA_PIN1_DIRECTION << 1) + (PORTA_PIN2_DIRECTION << 2) + (PORTA_PIN3_DIRECTION << 3) \
		+ (PORTA_PIN4_DIRECTION << 4) + (PORTA_PIN5_DIRECTION << 5) + (PORTA_PIN6_DIRECTION << 6) + (PORTA_PIN7_DIRECTION << 7))

#define PORTA_DIRECTION_CONFIG(PORTB_PIN0_DIRECTION,PORTB_PIN1_DIRECTION,PORTB_PIN2_DIRECTION,PORTB_PIN3_DIRECTION,PORTB_PIN4_DIRECTION,PORTB_PIN5_DIRECTION,PORTB_PIN6_DIRECTION,PORTB_PIN7_DIRECTION) (PORTB_PIN0_DIRECTION + (PORTB_PIN1_DIRECTION << 1) + (PORTB_PIN2_DIRECTION << 2) + (PORTB_PIN3_DIRECTION << 3) \
		+ (PORTB_PIN4_DIRECTION << 4) + (PORTB_PIN5_DIRECTION << 5) + (PORTB_PIN6_DIRECTION << 6) + (PORTB_PIN7_DIRECTION << 7))

#define PORTA_DIRECTION_CONFIG(PORTC_PIN0_DIRECTION,PORTC_PIN1_DIRECTION,PORTC_PIN2_DIRECTION,PORTC_PIN3_DIRECTION,PORTC_PIN4_DIRECTION,PORTC_PIN5_DIRECTION,PORTC_PIN6_DIRECTION,PORTC_PIN7_DIRECTION) (PORTC_PIN0_DIRECTION + (PORTC_PIN1_DIRECTION << 1) + (PORTC_PIN2_DIRECTION << 2) + (PORTC_PIN3_DIRECTION << 3) \
		+ (PORTC_PIN4_DIRECTION << 4) + (PORTC_PIN5_DIRECTION << 5) + (PORTC_PIN6_DIRECTION << 6) + (PORTC_PIN7_DIRECTION << 7))

#define PORTA_DIRECTION_CONFIG(PORTD_PIN0_DIRECTION,PORTD_PIN1_DIRECTION,PORTD_PIN2_DIRECTION,PORTD_PIN3_DIRECTION,PORTD_PIN4_DIRECTION,PORTD_PIN5_DIRECTION,PORTD_PIN6_DIRECTION,PORTD_PIN7_DIRECTION)	 (PORTD_PIN0_DIRECTION + (PORTD_PIN1_DIRECTION << 1) + (PORTD_PIN2_DIRECTION << 2) + (PORTD_PIN3_DIRECTION << 3) \
		+ (PORTD_PIN4_DIRECTION << 4) + (PORTD_PIN5_DIRECTION << 5) + (PORTD_PIN6_DIRECTION << 6) + (PORTD_PIN7_DIRECTION << 7))

#define PORTA_DIR	PORTA_DIRECTION_CONFIG(PORTA_PIN0_DIRECTION,PORTA_PIN1_DIRECTION,PORTA_PIN2_DIRECTION,PORTA_PIN3_DIRECTION,PORTA_PIN4_DIRECTION,PORTA_PIN5_DIRECTION,PORTA_PIN6_DIRECTION,PORTA_PIN7_DIRECTION)
#define	PORTB_DIR	PORTA_DIRECTION_CONFIG(PORTB_PIN0_DIRECTION,PORTB_PIN1_DIRECTION,PORTB_PIN2_DIRECTION,PORTB_PIN3_DIRECTION,PORTB_PIN4_DIRECTION,PORTB_PIN5_DIRECTION,PORTB_PIN6_DIRECTION,PORTB_PIN7_DIRECTION)
#define PORTC_DIR	PORTA_DIRECTION_CONFIG(PORTC_PIN0_DIRECTION,PORTC_PIN1_DIRECTION,PORTC_PIN2_DIRECTION,PORTC_PIN3_DIRECTION,PORTC_PIN4_DIRECTION,PORTC_PIN5_DIRECTION,PORTC_PIN6_DIRECTION,PORTC_PIN7_DIRECTION)
#define PORTD_DIR	PORTA_DIRECTION_CONFIG(PORTD_PIN0_DIRECTION,PORTD_PIN1_DIRECTION,PORTD_PIN2_DIRECTION,PORTD_PIN3_DIRECTION,PORTD_PIN4_DIRECTION,PORTD_PIN5_DIRECTION,PORTD_PIN6_DIRECTION,PORTD_PIN7_DIRECTION)


#endif /* DIO_CFG_H_ */
